"""Fix gender enum

Revision ID: 18f369952ea4
Revises: fbdd6e55e213
Create Date: 2025-05-21 01:47:44.390043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '18f369952ea4'
down_revision: Union[str, None] = 'fbdd6e55e213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'gender',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Enum('male', 'female', name='gender_enum'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'gender',
               existing_type=sa.Enum('male', 'female', name='gender_enum'),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
