"""change enum

Revision ID: db8ea42fa837
Revises: e31bd1647fde
Create Date: 2025-05-23 02:47:52.182147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'db8ea42fa837'
down_revision: Union[str, None] = 'e31bd1647fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'telecom',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Enum('SKT', 'KT', 'LGU', name='telecom_enum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'telecom',
               existing_type=sa.Enum('SKT', 'KT', 'LGU', name='telecom_enum'),
               type_=mysql.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###
