"""Modify phone_number to unique, remove status

Revision ID: fbdd6e55e213
Revises: 8fcf6cd38240
Create Date: 2025-05-21 01:40:44.571220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbdd6e55e213'
down_revision: Union[str, None] = '8fcf6cd38240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('birthdate', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('login_count', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq_user_phone_number'), 'user', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_phone_number'), 'user', type_='unique')
    op.drop_column('user', 'login_count')
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'birthdate')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
